# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,Entry, Text, Button, PhotoImage, IntVar, Radiobutton, messagebox

#from LoginPage import LoginPage
import requests
#from message import custom_messagebox
import subprocess
import requests
import json
# from Children import ChilderenPage
from childrenPage import children_function
from scores import center_window
username_value = ""
password_value = ""
token = ''


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH1 = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame7")


def relative_to_assets1(path: str) -> Path:
    return ASSETS_PATH1 / Path(path)

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH2 = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame1")

def relative_to_assets2(path: str) -> Path:
    return ASSETS_PATH2 / Path(path)




def SignUpPage(window):
    window.title('SignUp')

    def open_startTestPage():
        file_to_run_path = r"C:\YusrGP\YusrProject\startTestPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import startTestPage.py
        
    def open_childrenPage():
        children_function2(window)
    
    def open_informationPage():
        file_to_run_path = r"C:\YusrGP\YusrProject\informationPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import informationPage.py
        
    def open_HomePage():
        file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import HomePage.py
    
    def Go_loginPage():
        LoginPage(window)
    
    window.geometry("396x688")
    window.configure(bg = "#FFEDED")


    def handeSignup():

        name_value =  entry_1.get()
        age_value = radio_var.get()
        sex_value = radio_var_sex.get()
        password_value = entry_2.get()
        username_value =entry_3.get()
        final_sex = ""

        #Check if not empty
        if name_value != "" and age_value != 0 and sex_value != 0 and password_value != "" and  username_value != "":
            if sex_value == 1:
                final_sex = "ذكر"
            elif sex_value == 2:
                final_sex = "انثى"

            data = {
            "name":name_value,
            "username":username_value,
            "age":age_value,
            "sex":final_sex,
            "password":password_value,
            "password2":password_value
            }

            response = requests.post("http://127.0.0.1:8000/api/accounts/signup", data)
            result = json.loads(response.text)
            if "error" in result.keys() :
                messagebox.showinfo("خطأ", str(result["error"]))
                
            else:
                messagebox.showinfo("نجاح", str(result["success"]))
                LoginPage(window)

        else:
            messagebox.showerror("خطأ", "املأ كل الحقول")


    canvas = Canvas(
        window,
        bg = "#FFEDED",
        height = 688,
        width = 396,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets1("image_1.png"))
    image_1 = canvas.create_image(
        198.0,
        294.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets1("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=Go_loginPage,
        relief="flat"
    )
    button_1.place(
        x=126.71923828125,
        y=479.3958740234375,
        width=163.56884765625,
        height=72.2080078125
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets1("image_2.png"))
    image_2 = canvas.create_image(
        202.0,
        331.0,
        image=image_image_2
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets1("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=handeSignup,
        relief="flat"
    )
    button_2.place(
        x=98.7744140625,
        y=361.1982421875,
        width=211.45263671875,
        height=59.6051025390625
    )


    image_image_3 = PhotoImage(
        file=relative_to_assets1("image_3.png"))
    image_3 = canvas.create_image(
        198.0,
        128.0,
        image=image_image_3
    )



### sex ########################################################

    radio_var_sex = IntVar()

    def on_radio_button_select():
        selected_value_sex = radio_var_sex.get()

## male
    button_image_3 = PhotoImage(
        file=relative_to_assets1("button_3.png"))
    button_3 = Radiobutton(
        image=button_image_3,
        indicatoron=0,
        borderwidth=0,
        highlightthickness=0,
        variable=radio_var_sex,
        value=1,
        command=on_radio_button_select,
    )
    button_3.place(
        x=215.0,
        y=184.0,
        width=39.0,
        height=35.0
    )


## female
    button_image_4 = PhotoImage(
        file=relative_to_assets1("button_4.png"))
    button_4 = Radiobutton(
        image=button_image_4,
        indicatoron=0,
        borderwidth=0,
        highlightthickness=0,
        variable=radio_var_sex,
        value=2,
        command=on_radio_button_select,
    )
    button_4.place(
        x=147.0,
        y=184.0,
        width=39.0,
        height=35.0
    )



### ages ########################################################
    radio_var = IntVar()
    def on_radio_button_select():
        selected_value = radio_var.get()



    button_image_5 = PhotoImage(
        file=relative_to_assets1("button_5.png"))
    button_5 = Radiobutton(
        image=button_image_5,
        indicatoron=0,
        borderwidth=0,
        highlightthickness=0,
        variable=radio_var,
        value=7,
        command=on_radio_button_select,
    )
    button_5.place(
        x=239.0,
        y=123.0,
        width=39.0,
        height=35.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets1("button_6.png"))
    button_6 = Radiobutton(
        image=button_image_6,
        indicatoron=0,
        borderwidth=0,
        highlightthickness=0,
        variable=radio_var,
        value=9,
        command=on_radio_button_select,
    )
    button_6.place(
        x=121.0,
        y=123.0,
        width=39.0,
        height=35.0
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets1("button_7.png"))
    button_7 = Radiobutton(
        image=button_image_7,
        indicatoron=0,
        borderwidth=0,
        highlightthickness=0,
        variable=radio_var,
        value=8,
        command=on_radio_button_select,
    )
    button_7.place(
        x=181.0,
        y=123.0,
        width=39.0,
        height=35.0
    )


### ages ########################################################



    entry_image_1 = PhotoImage(
        file=relative_to_assets1("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        198.0,
        78.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#ED9999",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=124.5,
        y=62.0,
        width=147.0,
        height=31.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets1("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        202.5,
        340.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#ED9999",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=129.0,
        y=325.0,
        width=147.0,
        height=28.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets1("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        202.5,
        283.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#ED9999",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=129.0,
        y=268.0,
        width=147.0,
        height=28.0
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets1("image_4.png"))
    image_4 = canvas.create_image(
        199.0,
        639.0,
        image=image_image_4
    )

    button_image_8 = PhotoImage(
        file=relative_to_assets1("button_8.png"))
    button_8 = Button(
        image=button_image_8,
        borderwidth=0,
        highlightthickness=0,
        command=open_HomePage,
        relief="flat"
    )
    button_8.place(
        x=109.6796875,
        y=603.6416015625,
        width=93.6396484375,
        height=83.7166748046875
    )

    button_image_9 = PhotoImage(
        file=relative_to_assets1("button_9.png"))
    button_9 = Button(
        image=button_image_9,
        borderwidth=0,
        highlightthickness=0,
        command=open_startTestPage,
        relief="flat"
    )
    button_9.place(
        x=197.6796875,
        y=603.6416015625,
        width=93.6396484375,
        height=83.7166748046875
    )

    button_image_10 = PhotoImage(
        file=relative_to_assets1("button_10.png"))
    button_10 = Button(
        image=button_image_10,
        borderwidth=0,
        highlightthickness=0,
        command=open_informationPage,
        relief="flat"
    )
    button_10.place(
        x=283.6806640625,
        y=603.564453125,
        width=113.6396484375,
        height=83.8707275390625
    )

    button_image_11 = PhotoImage(
        file=relative_to_assets1("button_11.png"))
    button_11 = Button(
        image=button_image_11,
        borderwidth=0,
        highlightthickness=0,
        command=open_childrenPage,
        relief="flat"
    )
    button_11.place(
        x=18.525390625,
        y=603.92822265625,
        width=96.36865234375,
        height=83.731689453125
    )
    window.resizable(False, False)
    center_window(window)
    window.mainloop()

######################################## LoginPage ###########################################

def LoginPage(window):
    window.title('Login')

    def open_informationPage():
        file_to_run_path = r"C:\YusrGP\YusrProject\informationPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import informationPage.py
        
    def open_HomePage():
        file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import HomePage.py

    def open_childrenPage():
        children_function2(window)

    def open_startTestPage():
        file_to_run_path = r"C:\YusrGP\YusrProject\startTestPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import startTestPage.py

    def Go_signupPage():
        SignUpPage(window)
    
    window.geometry("396x688")
    window.configure(bg = "#FFEDED")
    
    def handelLogIn():
        global username_value
        global password_value
        username_value = entry_2.get()
        password_value = entry_1.get()
        
        global token
        data = {
            "username":username_value,
            "password":password_value
        }
        
        response = requests.post("http://127.0.0.1:8000/api/token/", data)
        result = json.loads(response.text)
        if "access" in result:
            token = result["access"]
            children_function(window, token)
        else:
            messagebox.showerror("خطأ", "خطأ في أسم المستخدم او كلمة السر")

    # window = Tk()



    canvas = Canvas(
        window,
        bg = "#FFEDED",
        height = 688,
        width = 396,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets2("image_1.png"))
    image_1 = canvas.create_image(
        205.0,
        373.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets2("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=handelLogIn,
        relief="flat"
    )
    button_1.place(
        x=125.71728515625,
        y=382.3961181640625,
        width=163.56884765625,
        height=72.2080078125
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets2("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=Go_signupPage,
        relief="flat"
    )
    button_2.place(
        x=125.71728515625,
        y=515.3961181640625,
        width=163.56884765625,
        height=72.2080078125
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets2("image_2.png"))
    image_2 = canvas.create_image(
        202.0,
        110.0,
        image=image_image_2
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets2("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        196.5,
        359.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#ED9999",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=120.5,
        y=340.0,
        width=152.0,
        height=37.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets2("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        196.5,
        286.5,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#ED9999",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=120.5,
        y=267.0,
        width=152.0,
        height=37.0
    )

    

    image_image_3 = PhotoImage(
        file=relative_to_assets2("image_3.png"))
    image_3 = canvas.create_image(
        199.0,
        639.0,
        image=image_image_3
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets2("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=open_HomePage,
        relief="flat"
    )
    button_3.place(
        x=109.6796875,
        y=603.6416015625,
        width=93.6396484375,
        height=83.7166748046875
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets2("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=open_startTestPage,
        relief="flat"
    )
    button_4.place(
        x=197.6796875,
        y=603.6416015625,
        width=93.6396484375,
        height=83.7166748046875
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets2("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=open_informationPage,
        relief="flat"
    )
    button_5.place(
        x=283.6806640625,
        y=603.564453125,
        width=113.6396484375,
        height=83.8707275390625
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets2("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=open_childrenPage,
        relief="flat"
    )
    button_6.place(
        x=18.525390625,
        y=603.92822265625,
        width=96.36865234375,
        height=83.731689453125
    )
    window.resizable(False, False)
    center_window(window)
    window.mainloop()

######################################## ChildrenPage ###########################################

def children_function2(window):
    window.title('Children')
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame6")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    #window = Tk()

    window.geometry("396x688")
    window.configure(bg = "#FFEDED")


    canvas = Canvas(
        window,
        bg = "#FFEDED",
        height = 688,
        width = 396,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        203.0,
        177.0,
        image=image_image_1
    )

    def open_HomePage():
        file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=open_HomePage,
        relief="flat"
    )
    button_1.place(
        x=23.17822265625,
        y=18.272918701171875,
        width=60.05078125,
        height=51.6392822265625
    )

    def open_LoginPage():
        LoginPage(window)

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=open_LoginPage,
        relief="flat"
    )
    button_2.place(
        x=112.0,
        y=383.0,
        width=182.904296875,
        height=62.66021728515625
    )
    window.resizable(False, False)
    center_window(window)
    window.mainloop()

