
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import pygame

from findScore import clear3, printScore3
from scores import center_window

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame13")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_ResultPage():
    clear3()
    file_to_run_path = r"C:\YusrGP\YusrProject\ResultPage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import ResultPage.py

window = Tk()
window.title('FinishTest')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    199.0,
    137.0,
    image=image_image_1
)

pygame.init()
def perform_action(event):
    sound = pygame.mixer.Sound(r"C:\YusrGP\YusrProject\assets\frame13\Finish2.mp3")
    sound.play()
canvas.tag_bind(image_1, "<Button-1>", perform_action)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    215.0,
    234.0,
    image=image_image_2
)
canvas.tag_bind(image_2, "<Button-1>", perform_action)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    204.0,
    406.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_ResultPage,
    relief="flat"
)
button_1.place(
    x=87.0,
    y=540.0,
    width=231.0,
    height=62.0
)
window.resizable(False, False)
center_window(window)
window.mainloop()
