
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import pygame

from findScore import clear, clear1, clear2, clear3
from scores import center_window

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame28")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_sectionThreePage():
    clear2()
    file_to_run_path = r"C:\YusrGP\YusrProject\sectionThreePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import sectionThreePage.py

def open_HomePage():
    clear()
    clear1()
    clear2()
    clear3()
    file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import HomePage.py

window = Tk()
window.title('FinishSection2')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    198.0,
    112.0,
    image=image_image_1
)

pygame.init()
def perform_action(event):
    sound = pygame.mixer.Sound(r"C:\YusrGP\YusrProject\assets\frame28\Finish1.mp3")
    sound.play()
canvas.tag_bind(image_1, "<Button-1>", perform_action)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    198.0,
    408.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_sectionThreePage,
    relief="flat"
)
button_1.place(
    x=87.0,
    y=552.0,
    width=226.0,
    height=56.909423828125
)

button_home_2 = PhotoImage(
    file=relative_to_assets("homeButton.png"))
home_2 = Button(
    image=button_home_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_HomePage,
    relief="flat"
)
home_2.place(
    x=307.0,
    y=19.0,
    width=60.05078125,
    height=51.6392822265625
)

window.resizable(False, False)
center_window(window)
window.mainloop()
