
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, IntVar, Radiobutton
from tkinter import messagebox

import pygame

from scores import addScore2, center_window
from findScore import clear, clear1, clear2, clear3

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame31")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_GamePage5():
    file_to_run_path = r"C:\YusrGP\YusrProject\GamePage5.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import GamePage5.py

def open_HomePage():
    clear()
    clear1()
    clear2()
    clear3()
    file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import HomePage.py

window = Tk()
window.title('Game')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    198.0,
    399.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    198.0,
    628.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    198.0,
    112.0,
    image=image_image_3
)

pygame.init()
def perform_action(event):
    sound = pygame.mixer.Sound(r"C:\YusrGP\YusrProject\assets\frame31\Game4.mp3")
    sound.play()
canvas.tag_bind(image_3, "<Button-1>", perform_action)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    198.0,
    359.0,
    image=image_image_4
)
#Radio_button
radio_var1 = IntVar()
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Radiobutton(
    image=button_image_2,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=1,
)
button_2.place(
    x=93.0,
    y=463.0,
    width=86.0,
    height=78.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Radiobutton(
    image=button_image_1,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=2,
)
button_1.place(
    x=223.0,
    y=468.0,
    width=83.0,
    height=79.0
)


def open_page_two():
    if radio_var1.get():
        score4 = 0
        if radio_var1.get()  == 2:
            score4 += 3
        addScore2(score4)
        #print("Score:", calcScore(score4))
        file_to_run_path = r"C:\YusrGP\YusrProject\GamePage5.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
    else:
       messagebox.showwarning(title="تنبيه", message="اختر ليتم نقلك للصفحة التالية")

#next_booton
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=open_page_two,
    relief="flat"
)
button_3.place(
    x=153.0,
    y=579.0,
    width=90.0,
    height=61.875
)

button_home_2 = PhotoImage(
    file=relative_to_assets("homeButton.png"))
home_2 = Button(
    image=button_home_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_HomePage,
    relief="flat"
)
home_2.place(
    x=307.0,
    y=19.0,
    width=60.05078125,
    height=51.6392822265625
)

window.resizable(False, False)
center_window(window)
window.mainloop()
