
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, IntVar, Radiobutton
from tkinter import messagebox

import pygame

from scores import addScore2, center_window
from findScore import clear, clear1, clear2, clear3

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame34")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def calculate_score():
    print("section2_score")


def open_GamePage2():
    file_to_run_path = r"C:\YusrGP\YusrProject\GamePage2.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import GamePage2.py

def open_HomePage():
    clear()
    clear1()
    clear2()
    clear3()
    file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy() # Close the current window
        #import HomePage.py

window = Tk()
window.title('Game')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    195.0,
    132.0,
    image=image_image_1
)

pygame.init()
def perform_action(event):
    sound = pygame.mixer.Sound(r"C:\YusrGP\YusrProject\assets\frame34\Game1.mp3")
    sound.play()
canvas.tag_bind(image_1, "<Button-1>", perform_action)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    198.0,
    628.0,
    image=image_image_2
)


radio_var1 = IntVar()
radio_var2 = IntVar()
radio_var3 = IntVar()

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_1_1 = Radiobutton(
    image=button_image_10,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=1,
        
        
)
button_1_1.place(
    x=56.0,
    y=278.0,
    width=90.0,
    height=79.354736328125
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_1_2 = Radiobutton(
    image=button_image_2,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=2,
        
        
)
button_1_2.place(
    x=153.0,
    y=278.0,
    width=90.0,
    height=79.0
)
button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_1_3 = Radiobutton(
    image=button_image_9,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=3,
        
        
)
button_1_3.place(
    x=249.0,
    y=278.0,
    width=90.0,
    height=79.354736328125
)
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_2_1 = Radiobutton(
    image=button_image_4,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var2,
    value=1,
        
        
)
button_2_1.place(
    x=56.0,
    y=378.0,
    width=90.0,
    height=80.0
)
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_2_2 = Radiobutton(
    image=button_image_3,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var2,
    value=2,
        
        
)
button_2_2.place(
    x=153.0,
    y=378.0,
    width=90.0,
    height=80.0
)



button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_2_3 = Radiobutton(
    image=button_image_5,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var2,
    value=3,
        
        
)
button_2_3.place(
    x=249.0,
    y=378.0,
    width=90.0,
    height=80.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_3_1 = Radiobutton(
    image=button_image_6,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var3,
    value=1,
        #command=on_radio_button_select,
        
)
button_3_1.place(
    x=56.0,
    y=477.0,
    width=90.0,
    height=81.0
)
button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_3_2 = Radiobutton(
    image=button_image_8,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var3,
    value=2,
        
        
)
button_3_2.place(
    x=153.0,
    y=477.0,
    width=90.0,
    height=81.0
)
button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_3_3 = Radiobutton(
    image=button_image_7,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var3,
    value=3,
        
)
button_3_3.place(
    x=249.0,
    y=477.0,
    width=90.0,
    height=81.0
)

def open_page_two():
    if radio_var1.get() and radio_var2.get() and radio_var3.get():
        score1 = 0
        if radio_var1.get() == 1:
            score1 += 3
        if radio_var1.get()  == 3:
            score1 += 3
        if radio_var2.get()  == 1:
            score1 += 3
        if radio_var2.get()  == 2:
            score1 += 3
        if radio_var3.get()  == 1:
            score1 += 3
        if radio_var3.get()  == 3:
            score1 += 3
        addScore2(score1)
        file_to_run_path = r"C:\YusrGP\YusrProject\GamePage2.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
        #window.destroy(), # Destroy the current window and open page two
        #import GamePage2
    else:
        messagebox.showwarning(title="تنبيه", message="اختر ليتم نقلك للصفحة التالية")

    #next_booton
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_page_two,
    relief="flat"
)
button_1.place(
    x=153.0,
    y=579.0,
    width=90.0,
    height=61.875
)


button_home_2 = PhotoImage(
    file=relative_to_assets("homeButton.png"))
home_2 = Button(
    image=button_home_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_HomePage,
    relief="flat"
)
home_2.place(
    x=307.0,
    y=19.0,
    width=60.05078125,
    height=51.6392822265625
)

window.resizable(False, False)
center_window(window)
window.mainloop()
