
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import subprocess
import pygame
import tkinter
import tkinter as tk
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, IntVar, Radiobutton
from tkinter import messagebox

from scores import addScore3, center_window
from findScore import clear, clear1, clear2, clear3

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def open_HomePage():
    clear()
    clear1()
    clear2()
    clear3()
    file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import HomePage.py

window = Tk()
window.title('Listen')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    203.0,
    623.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    202.0,
    272.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    211.0,
    355.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    211.0,
    492.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    196.0,
    131.0,
    image=image_image_5
)

pygame.init()
def perform_action(event):
    sound = pygame.mixer.Sound(r"C:\YusrGP\YusrProject\assets\frame8\Listen.mp3")
    sound.play()
canvas.tag_bind(image_5, "<Button-1>", perform_action)

#--------------- listen dal ----------------
pygame.mixer.init()
def play():
   pygame.mixer.music.load(r"C:\YusrGP\YusrProject\assets\frame8\dal.mp3")
   pygame.mixer.music.play(loops=1)
      
      #---------------------- radiobutton seittings and button -------------------- 
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=play,
    relief="flat"
)
button_1.place(
    x=173.0,
    y=296.0,
    width=51.0,
    height=42.0
)

#--------------- listen jeem ----------------
pygame.mixer.init()
def play():
   pygame.mixer.music.load(r"C:\YusrGP\YusrProject\assets\frame8\jeem.mp3")
   pygame.mixer.music.play(loops=1)
      
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=play,
    relief="flat"
)
button_2.place(
    x=175.0,
    y=437.0,
    width=47.0,
    height=43.0
)

# ---------- track the selected value of a radio button ----------
radio_var1 = IntVar()
radio_var2 = IntVar()

#button alef
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Radiobutton(
    image=button_image_3,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=1,
)
button_3.place(
    x=265.0,
    y=370.0,
    width=67.0,
    height=61.0
)
#button dal
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Radiobutton(
    image=button_image_4,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=2,
)
button_4.place(
    x=193.0,
    y=370.0,
    width=69.0,
    height=60.0
)
#button meem
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Radiobutton(
    image=button_image_5,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=3,
)
button_5.place(
    x=128.0,
    y=372.0,
    width=62.0,
    height=59.0
)
#button noon
button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Radiobutton(
    image=button_image_6,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var1,
    value=4,
)
button_6.place(
    x=55.0,
    y=372.0,
    width=65.0,
    height=59.0
)
#button 7a
button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Radiobutton(
    image=button_image_7,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var2,
    value=5,
)
button_7.place(
    x=231.0,
    y=510.0,
    width=62.0,
    height=60.0
)
#button 5a
button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Radiobutton(
    image=button_image_8,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var2,
    value=6,
)
button_8.place(
    x=154.0,
    y=510.0,
    width=63.0,
    height=60.0
)
#button jeem
button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Radiobutton(
    image=button_image_9,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable=radio_var2,
    value=7,
)
button_9.place(
    x=81.0,
    y=512.0,
    width=59.0,
    height=57.0
)


# ----------------- function nextpage and alert ------------------
def open_QafPage():
    if radio_var1.get() != 0 and radio_var2.get() != 0:
        score = 0
        if radio_var1.get() == 1:
            score += 2
        if radio_var1.get() == 3:
            score += 2
        if radio_var1.get() == 4:
            score += 2
        if radio_var2.get() == 5:
            score += 2
        if radio_var2.get() == 6:
            score += 2
        addScore3(score)
        file_to_run_path = r"C:\YusrGP\YusrProject\QafPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
       #window.destroy()  # Destroy the current window and open page two
       #import QafPage.py
    else:
       messagebox.showwarning(title="تنبيه", message="اختر ليتم نقلك للصفحة التالية")


# ----------------- button nextpage ------------------
button_image_10 = PhotoImage(file=relative_to_assets("button_10.png"))
button_10 = Button(
image=button_image_10,
borderwidth=0,
highlightthickness=0,
command=open_QafPage, # Call the function to open page two
relief="flat"
)

button_10.place(
    x=139.0,
    y=576.0,
    width=113.0,
    height=60.0
)

button_home_2 = PhotoImage(
    file=relative_to_assets("homeButton.png"))
home_2 = Button(
    image=button_home_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_HomePage,
    relief="flat"
)
home_2.place(
    x=307.0,
    y=19.0,
    width=60.05078125,
    height=51.6392822265625
)

window.resizable(False, False)
center_window(window)
window.mainloop()
