
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import subprocess
import requests
import json
# from Children import ChilderenPage
from childrenPage import children_function
from DatabasePages import LoginPage
from DatabasePages import SignUpPage

def Go_signupPage():
    SignUpPage(window)

if __name__ == "__main__":
    window = Tk()
    LoginPage(window)