
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, IntVar, Radiobutton, messagebox

from scores import center_window

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame19")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title('Mood')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    204.0,
    646.0,
    image=image_image_1
)

radio_var = IntVar()
def on_radio_button_select():
    selected_value = radio_var.get()
    print("Selected value:", selected_value)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    198.0,
    621.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    198.0,
    320.0,
    image=image_image_3
)

#
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Radiobutton(
    image=button_image_1,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable = radio_var,
    value="1"
)
button_1.place(
    x=206.0,
    y=177.0,
    width=156.0,
    height=150.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Radiobutton(
    image=button_image_2,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable = radio_var,
    value="2"
)
button_2.place(
    x=36.0,
    y=327.0,
    width=155.0,
    height=145.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Radiobutton(
    image=button_image_3,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable = radio_var,
    value="3"
)
button_3.place(
    x=36.0,
    y=177.0,
    width=156.0,
    height=150.0
)

#
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Radiobutton(
    image=button_image_4,
    indicatoron=0,
    borderwidth=0,
    highlightthickness=0,
    variable = radio_var,
    value="4"
)
button_4.place(
    x=206.0,
    y=327.0,
    width=155.0,
    height=145.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    196.0,
    100.0,
    image=image_image_4
)

def open_SectionTwoPage():
    if radio_var.get() == 1 or radio_var.get() == 2 or radio_var.get() == 4:
        file_to_run_path = r"C:\YusrGP\YusrProject\MoodMessage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
    elif radio_var.get() ==3:
        file_to_run_path = r"C:\YusrGP\YusrProject\FriendTaaloomPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
    else:
        messagebox.showwarning(title="تنبيه", message="اختر ليتم نقلك للصفحة التالية")
    #window.destroy() # Close the current window
    #import SectionTwoPage.py

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_SectionTwoPage,
    relief="flat"
)
button_5.place(
    x=147.0,
    y=505.0,
    width=97.46826171875,
    height=60.7379150390625
)
window.resizable(False, False)
center_window(window)
window.mainloop()
