
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import BOTH, LEFT, RIGHT, VERTICAL, Y, Frame, Label, Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox, ttk, Radiobutton, IntVar

from scores import addScore1, center_window
from findScore import clear1, printScore1, clear, clear2, clear3

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame16")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



def open_HomePage():
    clear()
    clear1()
    clear2()
    clear3()
    file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import HomePage.py

#def on_radio_button_select():
#    selected_value = radio_var.get()
#    print("Selected value:", selected_value)

window = Tk()
window.title('Questions')

window.geometry("396x688")
window.configure(bg = "#FFEDED")

main_frame = Frame(window)
main_frame.pack(fill=BOTH, expand=1)

canvas = Canvas(main_frame)
canvas.pack(side=LEFT, fill=BOTH, expand=1)

my_scrollbar = ttk.Scrollbar(main_frame, orient=VERTICAL, command=canvas.yview)
my_scrollbar.pack(side=RIGHT, fill=Y)

canvas.configure(yscrollcommand=my_scrollbar.set)
canvas.bind('<Configure>', lambda e: canvas.configure(scrollregion = canvas.bbox("all")))

second_frame = Frame(canvas)

canvas.create_window((0,0), window=second_frame, anchor="nw")

my_label = Label(second_frame)

#calcualting the score

def calculate_score():
    score = 0

    if score_var1.get() == 1:
        score += 1

    if score_var2.get() == 1:
        score += 1

    if score_var3.get() == 1:
        score += 1

    if score_var4.get() == 1:
        score += 1

    if score_var5.get() == 1:
        score += 1

    if score_var6.get() == 1:
        score += 1

    if score_var7.get() == 1:
        score += 1
    
    if score_var8.get() == 1:
        score += 1

    if score_var9.get() == 1:
        score += 1

    if score_var10.get() == 1:
        score += 1

    if score_var11.get() == 2:
        score += 1

    if score_var12.get() == 1:
        score += 1

    if score_var13.get() == 1:
        score += 1

    if score_var14.get() == 1:
        score += 1

    if score_var15.get() == 1:
        score += 1

    if score_var16.get() == 1:
        score += 1

    if score_var17.get() == 1:
        score += 1

    if score_var18.get() == 1:
        score += 1

    if score_var19.get() == 1:
        score += 1

    if score_var20.get() == 1:
        score += 1

    if score_var21.get() == 1:
        score -= 0

    if score_var22.get() == 1:
        score -= 0

    if score_var23.get() == 1:
        score -= 0

    if score_var24.get() == 1:
        score -= 0

    if score_var25.get() == 1:
        score -= 0

    if score_var26.get() == 1:
        score -= 0

    if score_var27.get() == 1:
        score -= 0

    if score_var28.get() == 1:
        score -= 0

    if score_var29.get() == 1:
        score += 1
    if score_var29.get() == 2:
        score -= 0

    if score_var30.get() == 1:
        score -= 0

    if score_var31.get() == 1:
        score += 1
    if score_var31.get() == 2:
        score -= 0

    if score_var32.get() == 1:
        score += 1
    if score_var32.get() == 2:
        score -= 0

    if score_var33.get() == 1:
        score += 1
    if score_var33.get() == 2:
        score -= 0

    if score_var34.get() == 1:
        score += 1
    if score_var34.get() == 2:
        score -= 0
    return score


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    198.0,
    546.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    198.0,
    447.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    198.0,
    348.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    198.0,
    249.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    198.0,
    150.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    210.0,
    59.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    198.0,
    645.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    198.0,
    744.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    198.0,
    843.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    198.0,
    942.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    198.0,
    1041.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    198.0,
    1140.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    198.0,
    1239.0,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    198.0,
    1338.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    198.0,
    1437.0,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    198.0,
    1536.0,
    image=image_image_16
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    198.0,
    1635.0,
    image=image_image_17
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    198.0,
    1734.0,
    image=image_image_18
)

image_image_19 = PhotoImage(
    file=relative_to_assets("image_19.png"))
image_19 = canvas.create_image(
    198.0,
    1833.0,
    image=image_image_19
)

image_image_20 = PhotoImage(
    file=relative_to_assets("image_20.png"))
image_20 = canvas.create_image(
    198.0,
    1932.0,
    image=image_image_20
)

image_image_21 = PhotoImage(
    file=relative_to_assets("image_21.png"))
image_21 = canvas.create_image(
    198.0,
    2031.0,
    image=image_image_21
)


image_image_22 = PhotoImage(
    file=relative_to_assets("image_22.png"))
image_22 = canvas.create_image(
    198.0,
    2145.0,
    image=image_image_22
)

image_image_23 = PhotoImage(
    file=relative_to_assets("image_23.png"))
image_23 = canvas.create_image(
    198.0,
    2254.0,
    image=image_image_23
)

image_image_24 = PhotoImage(
    file=relative_to_assets("image_24.png"))
image_24 = canvas.create_image(
    198.0,
    2353.0,
    image=image_image_24
)

image_image_25 = PhotoImage(
    file=relative_to_assets("image_25.png"))
image_25 = canvas.create_image(
    198.0,
    2452.0,
    image=image_image_25
)

image_image_26 = PhotoImage(
    file=relative_to_assets("image_26.png"))
image_26 = canvas.create_image(
    198.0,
    2551.0,
    image=image_image_26
)

image_image_27 = PhotoImage(
    file=relative_to_assets("image_27.png"))
image_27 = canvas.create_image(
    198.0,
    2650.0,
    image=image_image_27
)

image_image_28 = PhotoImage(
    file=relative_to_assets("image_28.png"))
image_28 = canvas.create_image(
    198.0,
    2749.0,
    image=image_image_28
)

image_image_29 = PhotoImage(
    file=relative_to_assets("image_29.png"))
image_29 = canvas.create_image(
    198.0,
    2848.0,
    image=image_image_29
)

image_image_30 = PhotoImage(
    file=relative_to_assets("image_30.png"))
image_30 = canvas.create_image(
    198.0,
    2947.0,
    image=image_image_30
)

image_image_31 = PhotoImage(
    file=relative_to_assets("image_31.png"))
image_31 = canvas.create_image(
    198.0,
    3046.0,
    image=image_image_31
)

image_image_32 = PhotoImage(
    file=relative_to_assets("image_32.png"))
image_32 = canvas.create_image(
    198.0,
    3145.0,
    image=image_image_32
)

image_image_33 = PhotoImage(
    file=relative_to_assets("image_33.png"))
image_33 = canvas.create_image(
    198.0,
    3244.0,
    image=image_image_33
)

image_image_34 = PhotoImage(
    file=relative_to_assets("image_34.png"))
image_34 = canvas.create_image(
    198.0,
    3343.0,
    image=image_image_34
)

image_image_35 = PhotoImage(
    file=relative_to_assets("image_35.png"))
image_35 = canvas.create_image(
    198.0,
    3467.0,
    image=image_image_35
)


#-------------------radio buttons are here!! -------------------------
score_var1 = IntVar()
score_var2 = IntVar()
score_var3 = IntVar()
score_var4 = IntVar()
score_var5 = IntVar()
score_var6 = IntVar()
score_var7 = IntVar()
score_var8 = IntVar()
score_var9 = IntVar()
score_var10 = IntVar()
score_var11 = IntVar()
score_var12 = IntVar()
score_var13 = IntVar()
score_var14 = IntVar()
score_var15= IntVar()
score_var16= IntVar()
score_var17 = IntVar()
score_var18 = IntVar()
score_var19 = IntVar()
score_var20 = IntVar()
score_var21 = IntVar()
score_var22= IntVar()
score_var23 = IntVar()
score_var24 = IntVar()
score_var25 = IntVar()
score_var26 = IntVar()
score_var27 = IntVar()
score_var28 = IntVar()
score_var29 = IntVar()
score_var30= IntVar()
score_var31 = IntVar()
score_var32 = IntVar()
score_var33= IntVar()
score_var34= IntVar()

yes_radio1 = Radiobutton(
    window,
    text="نعم",
    variable=score_var1,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    150, # Y-coordinate
    window=yes_radio1,
    anchor="nw"
)

no_radio1 = Radiobutton(
    window,
    text="لا",
    variable=score_var1,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    150, # Y-coordinate
    window=no_radio1,
    anchor="nw"
)

# ---------------------------------------------------

no_radio2 = Radiobutton(
    window,
    text="نعم",
    variable=score_var2,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    250, # Y-coordinate
    window=no_radio2,
    anchor="nw"
)

yes_radio2 = Radiobutton(
    window,
    text="لا",
    variable=score_var2,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    250, # Y-coordinate
    window=yes_radio2,
    anchor="nw"
)


# ---------------------------------------------------

no_radio3 = Radiobutton(
    window,
    text="نعم",
    variable=score_var3,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    350, # Y-coordinate
    window=no_radio3,
    anchor="nw"
)

yes_radio3 = Radiobutton(
    window,
    text="لا",
    variable=score_var3,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    350, # Y-coordinate
    window=yes_radio3,
    anchor="nw"
)

# ---------------------------------------------------

no_radio4 = Radiobutton(
    window,
    text="نعم",
    variable=score_var4,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    450, # Y-coordinate
    window=no_radio4,
    anchor="nw"
)

yes_radio4 = Radiobutton(
    window,
    text="لا",
    variable=score_var4,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    450, # Y-coordinate
    window=yes_radio4,
    anchor="nw"
)

# ---------------------------------------------------

no_radio5 = Radiobutton(
    window,
    text="نعم",
    variable=score_var5,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    550, # Y-coordinate
    window=no_radio5,
    anchor="nw"
)

yes_radio5 = Radiobutton(
    window,
    text="لا",
    variable=score_var5,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    550, # Y-coordinate
    window=yes_radio5,
    anchor="nw"
)

# ---------------------------------------------------

no_radio6 = Radiobutton(
    window,
    text="نعم",
    variable=score_var6,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    650, # Y-coordinate
    window=no_radio6,
    anchor="nw"
)

yes_radio6 = Radiobutton(
    window,
    text="لا",
    variable=score_var6,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    650, # Y-coordinate
    window=yes_radio6,
    anchor="nw"
)

# ---------------------------------------------------

no_radio7 = Radiobutton(
    window,
    text="نعم",
    variable=score_var7,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    750, # Y-coordinate
    window=no_radio7,
    anchor="nw"
)

yes_radio7 = Radiobutton(
    window,
    text="لا",
    variable=score_var7,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    750, # Y-coordinate
    window=yes_radio7,
    anchor="nw"
)

# ---------------------------------------------------

no_radio8 = Radiobutton(
    window,
    text="نعم",
    variable=score_var8,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    850, # Y-coordinate
    window=no_radio8,
    anchor="nw"
)

yes_radio8 = Radiobutton(
    window,
    text="لا",
    variable=score_var8,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    850, # Y-coordinate
    window=yes_radio8,
    anchor="nw"
)
# radio button9---------------------------------------------------

no_radio9 = Radiobutton(
    window,
    text="نعم",
    variable=score_var9,
    value=1,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    250, # X-coordinate
    950, # Y-coordinate
    window=no_radio9,
    anchor="nw"
)

yes_radio9 = Radiobutton(
    window,
    text="لا",
    variable=score_var9,
    value=2,
    bg="#EDD0D0",
    relief="flat"
)
canvas.create_window(
    150, # X-coordinate
    950, # Y-coordinate
    window=yes_radio9,
    anchor="nw"
)
# radio button10---------------------------------------------------
no_radio10 = Radiobutton(
window,
text="نعم",
variable=score_var10,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1050, # Y-coordinate
window=no_radio10,
anchor="nw"
)

yes_radio10 = Radiobutton(
window,
text="لا",
variable=score_var10,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1050, # Y-coordinate
window=yes_radio10,
anchor="nw"
)
# radio button11---------------------------------------------------
no_radio11 = Radiobutton(
window,
text="نعم",
variable=score_var11,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1150, # Y-coordinate
window=no_radio11,
anchor="nw"
)

yes_radio11 = Radiobutton(
window,
text="لا",
variable=score_var11,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1150, # Y-coordinate
window=yes_radio11,
anchor="nw"
)
# radio button12---------------------------------------------------
no_radio12 = Radiobutton(
window,
text="نعم",
variable=score_var12,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1252, # Y-coordinate
window=no_radio12,
anchor="nw"
)

yes_radio12 = Radiobutton(
window,
text="لا",
variable=score_var12,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1252, # Y-coordinate
window=yes_radio12,
anchor="nw"
)
# radio button13---------------------------------------------------
no_radio13 = Radiobutton(
window,
text="نعم",
variable=score_var13,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1350, # Y-coordinate
window=no_radio13,
anchor="nw"
)

yes_radio13 = Radiobutton(
window,
text="لا",
variable=score_var13,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1350, # Y-coordinate
window=yes_radio13,
anchor="nw"
)
# radio button14---------------------------------------------------
no_radio14 = Radiobutton(
window,
text="نعم",
variable=score_var14,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1450, # Y-coordinate
window=no_radio14,
anchor="nw"
)

yes_radio14 = Radiobutton(
window,
text="لا",
variable=score_var14,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1450, # Y-coordinate
window=yes_radio14,
anchor="nw"
)
# radio button15---------------------------------------------------
no_radio15 = Radiobutton(
window,
text="نعم",
variable=score_var15,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1550, # Y-coordinate
window=no_radio15,
anchor="nw"
)

yes_radio15 = Radiobutton(
window,
text="لا",
variable=score_var15,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1550, # Y-coordinate
window=yes_radio15,
anchor="nw"
)
# radio button16---------------------------------------------------
no_radio16 = Radiobutton(
window,
text="نعم",
variable=score_var16,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1650, # Y-coordinate
window=no_radio16,
anchor="nw"
)

yes_radio16 = Radiobutton(
window,
text="لا",
variable=score_var16,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1650, # Y-coordinate
window=yes_radio16,
anchor="nw"
)
# radio button17---------------------------------------------------
no_radio17 = Radiobutton(
window,
text="نعم",
variable=score_var17,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1750, # Y-coordinate
window=no_radio17,
anchor="nw"
)

yes_radio17 = Radiobutton(
window,
text="لا",
variable=score_var17,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1750, # Y-coordinate
window=yes_radio17,
anchor="nw"
)
# radio button18---------------------------------------------------
no_radio18 = Radiobutton(
window,
text="نعم",
variable=score_var18,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1850, # Y-coordinate
window=no_radio18,
anchor="nw"
)

yes_radio18 = Radiobutton(
window,
text="لا",
variable=score_var18,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1850, # Y-coordinate
window=yes_radio18,
anchor="nw"
)
# radio button19---------------------------------------------------
no_radio19 = Radiobutton(
window,
text="نعم",
variable=score_var19,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
1950, # Y-coordinate
window=no_radio19,
anchor="nw"
)

yes_radio19 = Radiobutton(
window,
text="لا",
variable=score_var19,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
1950, # Y-coordinate
window=yes_radio19,
anchor="nw"
)
# radio button20---------------------------------------------------
no_radio20 = Radiobutton(
window,
text="نعم",
variable=score_var20,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2030, # Y-coordinate
window=no_radio20,
anchor="nw"
)

yes_radio20 = Radiobutton(
window,
text="لا",
variable=score_var20,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2030, # Y-coordinate
window=yes_radio20,
anchor="nw"
)

###################################### محك التباين والتباعد# ##########################################

# radio button21---------------------------------------------------
no_radio21 = Radiobutton(
window,
text="نعم",
variable=score_var21,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2160, # Y-coordinate
window=no_radio21,
anchor="nw"
)

yes_radio21 = Radiobutton(
window,
text="لا",
variable=score_var21,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2160, # Y-coordinate
window=yes_radio21,
anchor="nw"
)
# radio button22---------------------------------------------------
no_radio22 = Radiobutton(
window,
text="نعم",
variable=score_var22,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2260, # Y-coordinate
window=no_radio22,
anchor="nw"
)

yes_radio22 = Radiobutton(
window,
text="لا",
variable=score_var22,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2260, # Y-coordinate
window=yes_radio22,
anchor="nw"
)
# radio button23---------------------------------------------------
no_radio23 = Radiobutton(
window,
text="نعم",
variable=score_var23,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2360, # Y-coordinate
window=no_radio23,
anchor="nw"
)

yes_radio23 = Radiobutton(
window,
text="لا",
variable=score_var23,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2360, # Y-coordinate
window=yes_radio23,
anchor="nw"
)
# radio button24---------------------------------------------------
no_radio24 = Radiobutton(
window,
text="نعم",
variable=score_var24,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2460, # Y-coordinate
window=no_radio24,
anchor="nw"
)

yes_radio24 = Radiobutton(
window,
text="لا",
variable=score_var24,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2460, # Y-coordinate
window=yes_radio24,
anchor="nw"
)
# radio button25---------------------------------------------------
no_radio25 = Radiobutton(
window,
text="نعم",
variable=score_var25,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2560, # Y-coordinate
window=no_radio25,
anchor="nw"
)

yes_radio25 = Radiobutton(
window,
text="لا",
variable=score_var25,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2560, # Y-coordinate
window=yes_radio25,
anchor="nw"
)
# radio button26---------------------------------------------------
no_radio26 = Radiobutton(
window,
text="نعم",
variable=score_var26,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2660, # Y-coordinate
window=no_radio26,
anchor="nw"
)

yes_radio26 = Radiobutton(
window,
text="لا",
variable=score_var26,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2660, # Y-coordinate
window=yes_radio26,
anchor="nw"
)

# radio button27---------------------------------------------------
no_radio27 = Radiobutton(
window,
text="نعم",
variable=score_var27,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2760, # Y-coordinate
window=no_radio27,
anchor="nw"
)

yes_radio27 = Radiobutton(
window,
text="لا",
variable=score_var27,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2760, # Y-coordinate
window=yes_radio27,
anchor="nw"
)
# radio button28---------------------------------------------------
no_radio28 = Radiobutton(
window,
text="نعم",
variable=score_var28,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2860, # Y-coordinate
window=no_radio28,
anchor="nw"
)

yes_radio28 = Radiobutton(
window,
text="لا",
variable=score_var28,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2860, # Y-coordinate
window=yes_radio28,
anchor="nw"
)
# radio button29---------------------------------------------------
no_radio29 = Radiobutton(
window,
text="نعم",
variable=score_var29,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
2960, # Y-coordinate
window=no_radio29,
anchor="nw"
)

yes_radio29 = Radiobutton(
window,
text="لا",
variable=score_var29,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
2960, # Y-coordinate
window=yes_radio29,
anchor="nw"
)
# radio button30---------------------------------------------------
no_radio30 = Radiobutton(
window,
text="نعم",
variable=score_var30,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
3060, # Y-coordinate
window=no_radio30,
anchor="nw"
)

yes_radio30 = Radiobutton(
window,
text="لا",
variable=score_var30,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
3060, # Y-coordinate
window=yes_radio30,
anchor="nw"
)
# radio button31---------------------------------------------------
no_radio31 = Radiobutton(
window,
text="نعم",
variable=score_var31,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
3160, # Y-coordinate
window=no_radio31,
anchor="nw"
)

yes_radio31 = Radiobutton(
window,
text="لا",
variable=score_var31,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
3160, # Y-coordinate
window=yes_radio31,
anchor="nw"
)
# radio button32---------------------------------------------------
no_radio32 = Radiobutton(
window,
text="نعم",
variable=score_var32,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
3250, # Y-coordinate
window=no_radio32,
anchor="nw"
)

yes_radio32 = Radiobutton(
window,
text="لا",
variable=score_var32,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
3250, # Y-coordinate
window=yes_radio32,
anchor="nw"
)
# radio button33---------------------------------------------------
no_radio33 = Radiobutton(
window,
text="جيد",
variable=score_var33,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
3350, # Y-coordinate
window=no_radio33,
anchor="nw"
)

yes_radio33 = Radiobutton(
window,
text="غير جيد",
variable=score_var33,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
3350, # Y-coordinate
window=yes_radio33,
anchor="nw"
)
# radio button34---------------------------------------------------
no_radio34 = Radiobutton(
window,
text="نعم",
variable=score_var34,
value=1,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
250, # X-coordinate
3480, # Y-coordinate
window=no_radio34,
anchor="nw"
)

yes_radio34 = Radiobutton(
window,
text="لا",
variable=score_var34,
value=2,
bg="#EDD0D0",
relief="flat"
)
canvas.create_window(
150, # X-coordinate
3480, # Y-coordinate
window=yes_radio34,
anchor="nw"
)

def open_BeforeTestPage():
    if score_var1.get() and score_var2.get() and score_var3.get() and score_var4.get() and score_var5.get() and score_var6.get() and score_var7.get() and score_var8.get() and score_var9.get() and score_var10.get() and score_var11.get() and score_var12.get() and score_var13.get() and score_var14.get() and score_var15.get() and score_var16.get() and score_var17.get() and score_var18.get() and score_var19.get() and score_var20.get() and score_var21.get() and score_var22.get() and score_var23.get() and score_var24.get() and score_var25.get() and score_var26.get() and score_var27.get() and score_var28.get() and score_var29.get() and score_var30.get() and score_var31.get() and score_var32.get() and score_var33.get() and score_var34.get() :
        addScore1(calculate_score())
        printScore1()
        clear1()
        file_to_run_path = r"C:\YusrGP\YusrProject\SectionTwoPage.py"
        window.destroy()
        subprocess.run(["python", file_to_run_path], check=True)
    else:
        messagebox.showwarning(title="تنبيه", message="املأ جميع الاجابات ليتم نقلك للصفحة التالية")
    #window.destroy()  # Close the current window
    #import BeforeTestPage.py # Import and run the code for page two

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_BeforeTestPage,
    relief="flat"
)
button_1.place(
    x=154.765625,
    y=3537.6310424804688,
    width=97.46875,
    height=60.7379150390625
)

canvas.create_window(
    154.765625,  # X-coordinate inside canvas
    3537.6310424804688,  # Y-coordinate inside canvas
    window=button_1,
    anchor="nw"
)

button_home_2 = PhotoImage(
    file=relative_to_assets("homeButton.png"))
home_2 = Button(
    image=button_home_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_HomePage,
    relief="flat"
)
home_2.place(
    x=13.0,
    y=18.0,
    width=60.05078125,
    height=51.6392822265625
)
canvas.create_window(
    13.0,  # X-coordinate inside canvas
    18.0,  # Y-coordinate inside canvas
    window=home_2,
    anchor="nw"
)

window.resizable(False, False)
center_window(window)
window.mainloop()