
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,Entry, Text, Button, PhotoImage, IntVar, Radiobutton, messagebox

from DatabasePages import LoginPage
from DatabasePages import SignUpPage

import requests
#from message import custom_messagebox

       
    
def Go_loginPage():
    LoginPage(window)

if __name__ == "__main__":
    window = Tk()
    SignUpPage(window)