
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from DatabasePages import children_function2
from scores import center_window

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\YusrGP\YusrProject\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_instructionsPage():
    file_to_run_path = r"C:\YusrGP\YusrProject\instructionsPage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import instructionsPage.py

def open_sectionOnePage():
    file_to_run_path = r"C:\YusrGP\YusrProject\sectionOnePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import sectionOnePage.py

def open_childrenPage():
    children_function2(window)

def open_informationPage():
    file_to_run_path = r"C:\YusrGP\YusrProject\informationPage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import informationPage.py

def open_HomePage():
    file_to_run_path = r"C:\YusrGP\YusrProject\HomePage.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)
    #window.destroy() # Close the current window
    #import HomePage.py

window = Tk()
window.title('Test')

window.geometry("396x688")
window.configure(bg = "#FFEDED")


canvas = Canvas(
    window,
    bg = "#FFEDED",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    204.0,
    154.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_instructionsPage,
    relief="flat"
)
button_1.place(
    x=110.0,
    y=330.0,
    width=187.10986328125,
    height=56.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_sectionOnePage,
    relief="flat"
)
button_2.place(
    x=109.0,
    y=419.0,
    width=187.10986328125,
    height=56.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    199.0,
    639.0,
    image=image_image_2
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=open_HomePage,
    relief="flat"
)
button_3.place(
    x=109.6796875,
    y=603.6416015625,
    width=93.6396484375,
    height=83.7166748046875
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
button_4.place(
    x=197.6796875,
    y=603.6416015625,
    width=93.6396484375,
    height=83.7166748046875
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_informationPage,
    relief="flat"
)
button_5.place(
    x=283.680419921875,
    y=603.564453125,
    width=113.6396484375,
    height=83.87078857421875
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=open_childrenPage,
    relief="flat"
)
button_6.place(
    x=18.525146484375,
    y=603.92822265625,
    width=96.369140625,
    height=83.731689453125
)
window.resizable(False, False)
center_window(window)
window.mainloop()
